/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef CacheServer_CONSTANTS_H
#define CacheServer_CONSTANTS_H

#include "CacheServer_types.h"



class CacheServerConstants {
 public:
  CacheServerConstants();

};

extern const CacheServerConstants g_CacheServer_constants;



#endif
