/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "CacheServer_constants.h"



const CacheServerConstants g_CacheServer_constants;

CacheServerConstants::CacheServerConstants() {
}



